CREATE SCHEMA IF NOT EXISTS FINANCEIRO DEFAULT CHARACTER SET utf8 ;
USE FINANCEIRO;

CREATE TABLE CONTASPAGAR (
	`CODIGO` INTEGER NOT NULL,
    `NOMECREDOR` VARCHAR(45),
    `VALORBRUTO` DOUBLE,
    `VALORDESCONTO` DOUBLE,
    `LIMITECREDITO` DOUBLE,
    `JUROS` DOUBLE,
    `ENDERECO` VARCHAR(100),
    `VALORPAGO` DOUBLE
);